[build]
  publish = "."
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
    
[[headers]]  
  for = "*.js"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate, max-age=0"
